### ISSUE TITLE
Update to use vcrpy-cleaner

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/splunk-soar-template#12]
Our core cleaner code now lives in
https://github.com/techservicesillinois/vcrpy-cleaner

Let's remove duplicate code here, and use that repository.

**Comment by mpitcel** [comment]
mypy [error](https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports) occurs because `vcr_cleaner` lacks type hints:

```
tests/conftest.py:8: error: Skipping analyzing "vcr_cleaner": module is installed, but missing library stubs or py.typed marker  [import]
tests/conftest.py:8: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 4 source files)
make: *** [Makefile:68: .static] Error 1
```

See ticket in `vcr_cleaner` repo to track changes: https://github.com/techservicesillinois/vcrpy-cleaner/issues/9
