### ISSUE TITLE
Add UUID test to avoid collisions

### ISSUE THREAD

**Issue by ddriddle** [techservicesillinois/splunk-soar-template#17]
It was reported that Midpoint disappeared from SOAR because TestBox shares the same UUID.

We should consider adding a test to the [template repo](https://github.com/techservicesillinois/splunk-soar-template/issues/new) to ensure the UUID is changed. We could have conditional tests in the Github Actions workflow that do not apply to the template itself only its copies in Github Actions if the conditional checks the repo name set in the environment.

We could add additional similar tests that would have the effect that the tests pass on the template repo itself but fail on copies. This would allow us to ensure that TODO are updated and that we do not accidentally overwrite other applications.

**Comment by zdc217** [comment]
Resolved with #18
