### ISSUE TITLE
Deployments failing after SOAR cloud update to 6.0.0

### ISSUE THREAD

**Issue by zdc217** [techservicesillinois/splunk-soar-template#25]
Deployments are failing when we push changes with the following error:

```
{"failed": true, "message": "Multiple app directories detected. Please make sure the app installation file was generated by the compilation script."}
```
Prior code that was deploying prior to 2/23/2023 is now failing with the same error. We tried a few things on our end, but noticed that Splunk SOAR updated to 6.0.0 yesterday: https://docs.splunk.com/Documentation/SOAR/current/ReleaseNotes/Enhancements

We suspect something may have changed on their end.

@spaldr is creating a case with Splunk to get some support for us.

**Comment by edthedev** [comment]
Two next steps per our collaboration with the SOAR team:

1. Unpack the .tgz they were able to use and look for difference. (See the Teams thread for the file.) I didn't find any obvious difference in a first look.
2. Try dropping the gzip step from our deployment, and just sending a .tar file.
3. Follow up with Splunk and ask for an updated working python or CURL example.
