### ISSUE TITLE
Add a debug_print of git_hash and action_id to the core action handler

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/splunk-soar-template#34]
## Context

It's pretty hard to tell what version is being used in a playbook. The git_hash in the logs in the Middpoint app has been really helpful, so we want to add these log lines to all our apps.

Also add git hash to a special 'output' field for easier access.

## Tasks

- [ ] copy these code lines into the template https://github.com/techservicesillinois/secops-splunk-illinois-midpoint/blob/f5e68d94d1251eb5e11402563c7cd07da8bb01ec/src/phIllinois_midPoint/illinoismidpoint_connector.py#L221-L222
- ~~add an output variable to the `.json` and add a line of code that saves the `git_hash` to it when handling an action.~~

**Comment by tzturner** [comment]
@edthedev this appears to be already handled [here](https://github.com/techservicesillinois/phantom-toolbox/blob/513d4a3ad2af4e80cdd89af0402d94045aa09f17/src/phtoolbox/app/base_connector.py#L38). Will close this ticket but please reopen if necessary.
