### ISSUE TITLE
Add our workflow for generating a downloadable app.tgz.zip file

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/splunk-soar-template#58]
## Context

We have needed to add this workflow to three projects now, so let's add it here so it's waiting for us.
https://github.com/techservicesillinois/secops-splunk-illinois-midpoint/blob/main/.github/workflows/app_tgz.yaml

## Tasks

- [x] copy in https://github.com/techservicesillinois/secops-splunk-illinois-midpoint/blob/main/.github/workflows/app_tgz.yaml
- [x] verify the app download asset gets generated

**Comment by mpitcel** [comment]
Draft PR open at https://github.com/techservicesillinois/splunk-soar-template/pull/64

**Comment by mpitcel** [comment]
Ready for review at https://github.com/techservicesillinois/splunk-soar-template/pull/64
